// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xh5dck-5-f2ZhbMRObMNB5G4crRuZFc',
    appId: '1:436776826745:web:e557f811d07172569ae1a8',
    messagingSenderId: '436776826745',
    projectId: 'blitzdatabase-4a130',
    authDomain: 'blitzdatabase-4a130.firebaseapp.com',
    storageBucket: 'blitzdatabase-4a130.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvUoLZBdw_nsqfN9uckmF6H22_upFUdq4',
    appId: '1:436776826745:android:7b31519d7cbbb68f9ae1a8',
    messagingSenderId: '436776826745',
    projectId: 'blitzdatabase-4a130',
    storageBucket: 'blitzdatabase-4a130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOd3yXilx_3GfmDglTgnULC94-Y33Dm4',
    appId: '1:436776826745:ios:f443c569ea495d639ae1a8',
    messagingSenderId: '436776826745',
    projectId: 'blitzdatabase-4a130',
    storageBucket: 'blitzdatabase-4a130.appspot.com',
    iosBundleId: 'com.example.blitz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOd3yXilx_3GfmDglTgnULC94-Y33Dm4',
    appId: '1:436776826745:ios:852f3396cbb9fa6b9ae1a8',
    messagingSenderId: '436776826745',
    projectId: 'blitzdatabase-4a130',
    storageBucket: 'blitzdatabase-4a130.appspot.com',
    iosBundleId: 'com.example.blitz.RunnerTests',
  );
}
